name: Format

on:
  pull_request:
    paths:
      - '**.swift'

jobs:
  swift_format:
    name: swift-format
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install
        run: brew install swift-format
      - name: Format
        run: make format
      - uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Run swift-format
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
